# Generated by Django 3.0.4 on 2020-03-22 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=25)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', models.CharField(default=None, max_length=25)),
                ('contactNo', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('firstName', models.CharField(default=None, max_length=15)),
                ('middleName', models.CharField(blank=True, max_length=15)),
                ('lastName', models.CharField(default=None, max_length=15)),
                ('profile_pic', models.TextField()),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
