# Generated by Django 3.0.4 on 2020-03-22 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('UID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=25)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', models.CharField(default=None, max_length=25)),
                ('contactNo', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('organisationName', models.CharField(max_length=30)),
                ('organisationLogo', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='individual',
            name='contactNo',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
