# Generated by Django 3.0.4 on 2020-03-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20200322_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationLogo',
            field=models.FileField(upload_to=''),
        ),
    ]
