# Generated by Django 3.0.4 on 2020-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20200322_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='individual',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='individual',
            name='houseNo_flatNo',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='individual',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='individual',
            name='pincode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='individual',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='individual',
            name='street',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='houseNo_flatNo',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pincode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='street',
            field=models.CharField(default='', max_length=20),
        ),
    ]
