# Generated by Django 3.0.4 on 2020-03-22 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20200322_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('BID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('noOfEmployees', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('CID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_info.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('RID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='ReviewConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10)),
                ('targetID', models.CharField(max_length=10)),
                ('RID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Review')),
            ],
        ),
        migrations.CreateModel(
            name='OBJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.BulkJob')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='JobsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=15)),
                ('basePay', models.FloatField()),
                ('timePeriodOfService', models.DurationField()),
                ('negotiable', models.BinaryField()),
                ('DOP', models.DateField()),
                ('noOfRequiredPersonnel', models.PositiveIntegerField()),
                ('JID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganisationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Organisation')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='FOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10)),
                ('JID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='EBJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.BulkJob')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Individual')),
            ],
        ),
    ]
