# Generated by Django 3.0.4 on 2020-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_bulkjob_category_ebj_foi_follows_jobs_jobsavailable_obj_review_reviewconnector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkjob',
            options={'verbose_name': 'Bulk Jobs', 'verbose_name_plural': 'Bulk Jobs'},
        ),
        migrations.AlterModelOptions(
            name='ebj',
            options={'verbose_name': 'Employee to Bulk Job Connector', 'verbose_name_plural': 'Employee to Bulk Job Connector'},
        ),
        migrations.AlterModelOptions(
            name='foi',
            options={'verbose_name': 'FOI', 'verbose_name_plural': 'FOI'},
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name': 'Follows', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='jobsavailable',
            options={'verbose_name': 'Jobs Available', 'verbose_name_plural': 'Jobs Available'},
        ),
        migrations.AlterModelOptions(
            name='obj',
            options={'verbose_name': 'Organisation to Bulk Job Connector', 'verbose_name_plural': 'Organisation to Bulk Job Connector'},
        ),
    ]
