# Generated by Django 3.0.4 on 2020-03-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20200324_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foi',
            options={'verbose_name': 'Field Of Interest', 'verbose_name_plural': 'Field Of Interest'},
        ),
        migrations.AlterModelOptions(
            name='reviewconnector',
            options={'verbose_name': 'Review Connector', 'verbose_name_plural': 'Review Connector'},
        ),
    ]
