# Generated by Django 3.0.4 on 2020-03-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20200324_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
