# Generated by Django 3.0.4 on 2020-03-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_auto_20200324_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs', 'verbose_name_plural': 'Jobs'},
        ),
    ]
