# Generated by Django 3.0.8 on 2020-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_auto_20200324_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='BID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='CID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foi',
            name='UID',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='individual',
            name='UID',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='JID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='UID',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='RID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewconnector',
            name='UID',
            field=models.CharField(max_length=36),
        ),
    ]
