# Generated by Django 3.0.8 on 2020-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_auto_20200716_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='UID',
            field=models.CharField(default=0, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='UID',
            field=models.CharField(default=0, max_length=36, primary_key=True, serialize=False),
        ),
    ]
