# Generated by Django 3.0.8 on 2020-07-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_auto_20200716_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='UID',
        ),
        migrations.AddField(
            model_name='individual',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsavailable',
            name='UID',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationLogo',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
