# Generated by Django 3.0.8 on 2020-07-16 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_auto_20200716_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='individual',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='UID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
