# Generated by Django 3.0.8 on 2020-07-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0015_auto_20200716_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebj',
            old_name='bulk',
            new_name='BID',
        ),
        migrations.RenameField(
            model_name='ebj',
            old_name='user',
            new_name='UID',
        ),
        migrations.RenameField(
            model_name='foi',
            old_name='job',
            new_name='JID',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='organisation',
            new_name='OrganisationID',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user',
            new_name='UID',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='category',
            new_name='CID',
        ),
        migrations.RenameField(
            model_name='jobsavailable',
            old_name='job',
            new_name='JID',
        ),
        migrations.RenameField(
            model_name='obj',
            old_name='bulk',
            new_name='BID',
        ),
        migrations.RenameField(
            model_name='obj',
            old_name='user',
            new_name='UID',
        ),
        migrations.RenameField(
            model_name='reviewconnector',
            old_name='rewiev',
            new_name='RID',
        ),
        migrations.RenameField(
            model_name='reviewconnector',
            old_name='target',
            new_name='UID',
        ),
        migrations.RemoveField(
            model_name='foi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobsavailable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewconnector',
            name='user',
        ),
        migrations.AddField(
            model_name='foi',
            name='UID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsavailable',
            name='UID',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewconnector',
            name='targetID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='BID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='CID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='UID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='JID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='UID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationLogo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='RID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
